"""Search view — search across all daily vault files.

Search is submit-based (not live). Results are generated by iterating
daily files and calling parse_entries on each.
"""

import re
from datetime import date
from pathlib import Path
from typing import cast

from textual.screen import Screen
from textual.app import ComposeResult
from textual.binding import Binding
from textual.containers import Vertical, ScrollableContainer
from textual.widgets import Input, Static, ListView, ListItem

from bujo.models import parse_entries
from bujo.vault import read_text_safe
from bujo.symbols import SYMBOL_DISPLAY, SYMBOL_COLORS


def search_vault(query: str, vault: Path) -> list[dict]:
    """Search all daily files for entries matching query.

    Returns list of dicts: {date, symbol, display, text, type}
    sorted newest first.
    """
    if not query.strip():
        return []

    query_lower = query.lower()
    daily = vault / "daily"
    if not daily.exists():
        return []

    results: list[dict] = []
    for f in sorted(daily.glob("*.md"), reverse=True):
        try:
            file_date = date.fromisoformat(f.stem)
        except ValueError:
            continue
        content = read_text_safe(f)
        entries = parse_entries(content, f, file_date)
        for entry in entries:
            if query_lower in entry.text.lower():
                results.append({
                    "date": file_date.isoformat(),
                    "symbol": entry.symbol,
                    "display": entry.display,
                    "text": entry.text,
                    "type": entry.type,
                })

    return results


class SearchView(Screen):
    """Inline search screen. / to open, Escape to close."""

    BINDINGS = [
        Binding("escape", "close_search", "Close"),
    ]

    def compose(self) -> ComposeResult:
        with Vertical(id="search-layout"):
            yield Input(placeholder="search entries...", id="search-input")
            yield ScrollableContainer(
                Static("[dim]type a query and press Enter[/dim]", id="search-status"),
                ListView(id="search-results"),
                id="search-scroll",
            )

    def on_mount(self) -> None:
        self.query_one("#search-input", Input).focus()

    def on_input_submitted(self, event: Input.Submitted) -> None:
        from bujo.vault import VAULT
        query = event.value.strip()
        results = search_vault(query, VAULT)

        lv = self.query_one("#search-results", ListView)
        lv.clear()
        status = self.query_one("#search-status", Static)

        if not results:
            status.update(f'[dim]no results for "{query}"[/dim]')
            return

        status.update(f"[dim]{len(results)} result{'s' if len(results) != 1 else ''}[/dim]")
        for r in results:
            display = SYMBOL_DISPLAY.get(r["symbol"], r["symbol"])
            color = SYMBOL_COLORS.get(r["symbol"], "white")
            label = f"[dim]{r['date']}[/dim]  [{color}]{display}[/] {r['text']}  [dim italic]{r['type']}[/dim italic]"
            lv.append(ListItem(Static(label)))

    def on_list_view_selected(self, event: ListView.Selected) -> None:
        """Jump to selected day when a search result is picked."""
        item = event.item
        label_str = str(item.children[0].renderable) if item.children else ""  # type: ignore[misc]
        match = re.search(r"(\d{4}-\d{2}-\d{2})", label_str)
        if match:
            target = date.fromisoformat(match.group(1))
            self.dismiss(target)

    def action_close_search(self) -> None:
        self.app.pop_screen()
